In [1]:
%matplotlib inline

Use Imagenet to tag your own photos
===

In this lab, we'll use an existing network (Xception) to tag our own photos.

Load an image
---

We'll use the Keras interface to the Pillow library to load up images. But then we'll have to manipulate them by hand.

Our following models will use values between $-1$ and $1$ instead of $0$ and $255$ for pixels.

- check what `x` looks like: `numpy`'s `.shape` attribute and a simple `print` call will do wonders!

- transform `x` so that its values shift from $[0, 255]$ to $[-1, 1]$.

In [7]:
from keras.preprocessing import image
import numpy as np

def _load_img(path):
    img = image.load_img(path, target_size=(299, 299))
    x = image.img_to_array(img)
    x = np.expand_dims(x, axis=0)
    return x

def _process_img(img):
    img /= 255
    img -= 0.5
    img *= 2
    return img

def process_imgs(paths):
    return np.concatenate([_process_img(_load_img(path)) for path in paths])

img = _load_img('pics/dogs.jpg')
print(img.shape)
print(img)
print(_process_img(img))

(1, 299, 299, 3)
[[[[ 226.  226.  228.]
   [ 226.  226.  228.]
   [ 226.  226.  228.]
   ..., 
   [ 226.  226.  228.]
   [ 227.  227.  229.]
   [ 227.  227.  229.]]

  [[ 226.  226.  228.]
   [ 226.  226.  228.]
   [ 226.  226.  228.]
   ..., 
   [ 227.  225.  228.]
   [ 226.  226.  228.]
   [ 226.  226.  228.]]

  [[ 226.  226.  228.]
   [ 226.  226.  228.]
   [ 225.  225.  227.]
   ..., 
   [ 226.  226.  228.]
   [ 226.  226.  228.]
   [ 226.  226.  228.]]

  ..., 
  [[ 134.  151.   83.]
   [ 139.  152.  109.]
   [ 113.  134.   67.]
   ..., 
   [  96.  116.   44.]
   [  89.  109.   37.]
   [  85.  102.   31.]]

  [[ 130.  150.   78.]
   [ 131.  153.   81.]
   [ 113.  135.   71.]
   ..., 
   [  99.  121.   48.]
   [  95.  116.   41.]
   [  91.  107.   36.]]

  [[ 126.  146.   74.]
   [ 124.  146.   74.]
   [ 111.  132.   63.]
   ..., 
   [  95.  117.   45.]
   [  97.  115.   41.]
   [  94.  112.   38.]]]]
[[[[ 0.77254903  0.77254903  0.78823531]
   [ 0.77254903  0.77254903  0.78823531

Import an existing model
---

Keras applications contains a lot of high performing models. In this lab, we'll use the Xception model.

- load the Xception network in the model variable.

In [3]:
from keras.applications.xception import Xception

model = Xception(weights='imagenet')

Plot the model
---

- plot the model thanks to Keras awesome visualization facilities :)

In [4]:
from keras.utils import plot_model

plot_model(model, to_file='xception-architecture.png')


Predit classes
---

We can now finally predict classes from our images thanks to our model! To do so, we'll use the helper function decode_predictions from `imagenet_utils` of Keras.

- define the predict_list function so that it takes as input preprocessed images and output a list of top 3 classes names.

In [8]:
from keras.applications.imagenet_utils import decode_predictions


def predict_list(imgs):
    preds = model.predict(imgs)
    preds = decode_predictions(preds, top=3)
    preds = [[name for (_, name, _) in top] for top in preds]
    return preds

imgs = process_imgs(['pics/bird.jpg', 'pics/car.jpg', 'pics/dogs.jpg'])

predict_list(imgs)

[['goose', 'prairie_chicken', 'bustard'],
 ['sports_car', 'convertible', 'beach_wagon'],
 ['Shih-Tzu', 'Lhasa', 'Pekinese']]

In [14]:
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
sns.set(style="white", context="talk")
rs = np.random.RandomState(7)


# Generate some sequential data
x = np.arange(1, 256)
y1 = np.arange(1, 256)
sns.barplot(x, y1, palette="BuGn_d", ax=ax1)

# Finalize the plot
sns.despine(bottom=True)
plt.setp(f.axes, yticks=[])
plt.tight_layout(h_pad=3)
plt.show()